# Generated by Django 3.2.12 on 2022-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mascota_tipo',
            field=models.CharField(max_length=200, null=True, verbose_name='Tipo de Mascota'),
        ),
        migrations.AddField(
            model_name='test',
            name='raza',
            field=models.CharField(max_length=200, null=True, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='test',
            name='nombre',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
