# Generated by Django 3.2.12 on 2022-02-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20220217_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Mascota',
        ),
    ]
